services:
  backend: &daiquiri
    image: linea/lsp_daiquiri:${IMAGE_TAG:-latest}
    command: /start.sh
    user: "1000:10006"
    env_file:
      - .env
    volumes:
      # Local Vars
      - ./local_settings.py:/app/config/settings/local.py:ro
      # Diretório de logs
      - ./logs:/var/log/daiquiri
      - ./logs:/var/log/celery
      # Diretórios onde o backend pode manipular arquivos.
      - ./data/files:/data/files
      - ./data/download:/data/download
      - ./data/upload:/data/upload
      # Django SAML
      - ./certificates:/app/certificates
    depends_on:
      rabbit:
        condition: service_healthy

  celery_flower: &daiquiri_celery_flower
    <<: *daiquiri
    command: celery -A config flower --url-prefix=flower
    depends_on:
      - backend

  rabbit:
    image: rabbitmq:3-management
    env_file:
      - .env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  # Servidor Web NGINX
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 8002:80
    volumes:
      # Arquivo de configuração do Ngnix para este ambiente.
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Diretório onde o backend manipula arquivos, e que deve ficar acessivel ao servidor web.
      - ./data/download:/data/download
      # Diretório de logs do servidor web.
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
      - celery_flower
      - rabbit
