# Generated by Django 4.2.13 on 2024-06-17 19:02

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesindexpage",
            name="intro",
        ),
        migrations.AddField(
            model_name="servicesindexpage",
            name="body",
            field=wagtailmarkdown.fields.MarkdownField(default=""),
        ),
    ]
