version: '3.9'

services:
  daiquiri:
    build:
      context: .
      dockerfile: ./Dockerfile
    # user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./daiquiri:/app
      - ./local.py:/app/config/settings/local.py:ro
      - ./fixtures:/app/fixtures
      - ./data/log:/data/log/
      - ./data/files:/data/files
      - ./data/download:/data/download
      - ./data/upload:/data/upload
    command: /start.sh
    depends_on:
      - database

  database:
    # image: postgres:latest
    image: postgres:13.9-alpine
    restart: always
    # restart: unless-stopped
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-data:/var/lib/postgresql/data
      - ./database_sample:/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - 54322:5432

    # adminer:
    #   image: adminer
    #   restart: always
    # rabbitmq:
    #   image: rabbitmq:3.11.8-management-alpine
    #   # ports:
    #   #  - 5672:5672
    #   # - 15672:15672
    #   volumes:
    #     - rabbitmq-data:/var/lib/rabbitmq/
    #     # - ./log/rabbitmq/:/var/log/rabbitmq
    #   environment:
    #     RABBITMQ_DEFAULT_USER: guest
    #     RABBITMQ_DEFAULT_PASS: guest
    #     RABBITMQ_DEFAULT_VHOST: daiquiri_vhost

    # Servidor Web NGINX
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      # Arquivo de configuração do Ngnix para este ambiente.
      - ./nginx-proxy-development.conf:/etc/nginx/conf.d/default.conf:ro
      # Diretório onde o backend manipula arquivos, e que deve ficar acessivel ao servidor web.
      - ./data/download:/data/download
      # Diretório de logs do servidor web. 
      - ./log:/var/log/nginx
    depends_on:
      - daiquiri

volumes:
  postgres-data:      
    # volumes:
    #   postgres-data:
    # daiquiri-data:
    # rabbitmq-data:

    # networks:
    #   daiquiri-network:
    #     driver: bridge
    #     external:


    # daiquiri:
    #   image: linea/lsp_daiquiri:b0536ad
    #   command: ./entrypoint.sh
    #   env_file:
    #     - .env_lsp_daiquiri
    #   volumes:
    #     # Local Vars
    #     - .local_vars_lsp_daiquiri.py:/app/config/settings/local.py:ro
    #     # Diretório de logs do Daiquiri
    #     - ./log/lsp_daiquiri:/data/log/
    #     # Diretórios onde o backend pode manipular arquivos. 
    #     - ./tmp_data/files:/data/files
    #     - ./tmp_data/download:/data/download
    #     - ./tmp_data/upload:/data/upload
