version: '3.9'
# Exemplo de como declarar variaveis comuns aos serviços
# https://www.section.io/engineering-education/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/
# 
# x-common-variables: &common-variables
#   MYSQL_DATABASE: books
#   MYSQL_USER: MYSQL_USER
#   MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  daiquiri: &daiquiri
    build:
      context: .
      dockerfile: ./Dockerfile
    # user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./daiquiri:/app
      - ./local.py:/app/config/settings/local.py:ro
      - ./fixtures:/app/fixtures
      - ./data/files:/data/files
      - ./data/download:/data/download
      - ./data/upload:/data/upload
      - ./data/log:/data/log/     
      - ./data/log/celery:/var/log/celery      
    command: /start.sh
    depends_on:
      - database
      - rabbit

  celery_flower: &celery_flower
    <<: *daiquiri
    command: celery -A config flower --url-prefix=flower
    depends_on:
      - daiquiri

  database:
    # image: postgres:latest
    image: postgres:13.9-alpine
    #restart: always
    # restart: unless-stopped
    volumes:
      # - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-data:/var/lib/postgresql/data
      - ./database_sample:/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - 54322:5432

  # Message-Broker Software RabbitMQ
  rabbit:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: daiquiri
      RABBITMQ_DEFAULT_PASS: adminadmin
      RABBITMQ_DEFAULT_VHOST: daiquiri_vhost
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/

  # Servidor Web NGINX
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      # Arquivo de configuração do Ngnix para este ambiente.
      - ./nginx-proxy-development.conf:/etc/nginx/conf.d/default.conf:ro
      # Diretório onde o backend manipula arquivos, e que deve ficar acessivel ao servidor web.
      - ./data/download:/data/download
      # Diretório de logs do servidor web. 
      - ./data/log/nginx:/var/log/nginx
    depends_on:
      - daiquiri
volumes:
  postgres-data:      
  rabbitmq-data:
