#!/bin/bash
set -e
# GRANT CREATE ON DATABASE daiquiri_data TO $POSTGRES_USER;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE daiquiri_app WITH OWNER $POSTGRES_USER;
    CREATE DATABASE daiquiri_data WITH OWNER $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE daiquiri_data TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "daiquiri_data" <<-EOSQL
    CREATE SCHEMA tap_schema AUTHORIZATION $POSTGRES_USER;
    CREATE SCHEMA tap_upload AUTHORIZATION $POSTGRES_USER;
    CREATE SCHEMA oai_schema AUTHORIZATION $POSTGRES_USER;
EOSQL