# Generated by Django 4.2.13 on 2024-06-17 17:09

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataindexpage",
            name="body",
            field=wagtailmarkdown.fields.MarkdownField(default=""),
        ),
    ]
