# Generated by Django 4.2.13 on 2024-06-17 17:09

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataindexpage",
            name="body",
            field=wagtailmarkdown.fields.MarkdownField(default=""),
        ),
    ]
