# Generated by Django 4.2.13 on 2024-06-17 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_dataindexpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataindexpage",
            name="intro",
        ),
    ]
