#!/bin/bash
set -e
# GRANT CREATE ON DATABASE daiquiri_data TO $POSTGRES_USER;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE daiquiri_app WITH OWNER $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE daiquiri_app TO $POSTGRES_USER;
    CREATE DATABASE daiquiri_data WITH OWNER $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE daiquiri_data TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "daiquiri_data" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS tap_schema;
    CREATE SCHEMA IF NOT EXISTS oai_schema;
    GRANT ALL ON SCHEMA tap_schema TO $POSTGRES_USER;
    GRANT ALL ON SCHEMA oai_schema TO $POSTGRES_USER;
EOSQL
