#!/bin/bash
set -e
# GRANT CREATE ON DATABASE daiquiri_data TO $POSTGRES_USER;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE daiquiri_app WITH OWNER $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE daiquiri_app TO $POSTGRES_USER;
EOSQL

